# GitHub action to build

name: Build

on:
  push:
    branches:
      - main
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker:20.10.9 # Specify the Docker version you need

    env:
      JACKSON_PRODUCT_ID: boxyhq
      JACKSON_WEBHOOK_SECRET: your-webhook-secret
      JACKSON_API_KEY: secret

    steps:
      - name: ls
        run: |
          ls -all -h
      - name: pwd
        run: |
          pwd
      - name: Build Docker image
        run: |
          docker build -t my-docker-image .
